-- 004_patch_transaccion_detalle_venta_costo.sql
-- Patch contable: detalle operativo para transacciones de VENTA y COSTO.
-- Permite que una transacción contable tenga detalle comercial/de costo separado
-- de sus movimientos de debe/haber en contabilidad.transaccion_movimiento_cuenta.

CREATE TABLE IF NOT EXISTS contabilidad.transaccion_detalle_venta (
    id_detalle_venta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_transaccion bigint NOT NULL,
    numero_linea integer NOT NULL DEFAULT 1,
    id_cliente bigint,
    id_producto_educativo bigint,
    id_producto_tienda bigint,
    id_curso_version bigint,
    id_clase_por_hora bigint,
    id_tienda bigint,
    id_sucursal bigint,
    id_cuenta_ingreso bigint,
    descripcion character varying(300),
    cantidad numeric(18,6) NOT NULL DEFAULT 1,
    precio_unitario numeric(18,6) NOT NULL DEFAULT 0,
    porcentaje_descuento numeric(9,6) NOT NULL DEFAULT 0,
    monto_descuento numeric(18,6) NOT NULL DEFAULT 0,
    monto_subtotal numeric(18,6) NOT NULL DEFAULT 0,
    porcentaje_impuesto numeric(9,6) NOT NULL DEFAULT 0,
    monto_impuesto numeric(18,6) NOT NULL DEFAULT 0,
    monto_total numeric(18,6) NOT NULL DEFAULT 0,
    moneda character varying(3) NOT NULL DEFAULT 'BOB',
    observaciones text,
    estado_registro character varying(20) DEFAULT 'Activo'::character varying,
    fecha_registro timestamp with time zone DEFAULT now(),
    fecha_modificacion timestamp with time zone,
    version_registro integer DEFAULT 1,
    id_usuario_creador bigint,
    id_usuario_modificacion bigint,
    CONSTRAINT ck_transaccion_detalle_venta_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_transaccion_detalle_venta_precio CHECK (precio_unitario >= 0),
    CONSTRAINT ck_transaccion_detalle_venta_descuento CHECK (porcentaje_descuento >= 0 AND porcentaje_descuento <= 100),
    CONSTRAINT ck_transaccion_detalle_venta_impuesto CHECK (porcentaje_impuesto >= 0 AND porcentaje_impuesto <= 100),
    CONSTRAINT ck_transaccion_detalle_venta_montos CHECK (
      monto_descuento >= 0 AND monto_subtotal >= 0 AND monto_impuesto >= 0 AND monto_total >= 0
    ),
    CONSTRAINT ck_transaccion_detalle_venta_producto CHECK (
      id_producto_educativo IS NOT NULL
      OR id_producto_tienda IS NOT NULL
      OR id_curso_version IS NOT NULL
      OR id_clase_por_hora IS NOT NULL
      OR descripcion IS NOT NULL
    )
);

CREATE TABLE IF NOT EXISTS contabilidad.transaccion_detalle_costo (
    id_detalle_costo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_transaccion bigint NOT NULL,
    numero_linea integer NOT NULL DEFAULT 1,
    id_centro_costo bigint,
    id_concepto_costo bigint,
    id_centro_costo_mapa bigint,
    id_proveedor bigint,
    id_empleado bigint,
    id_departamento bigint,
    id_bien bigint,
    id_movimiento_detalle bigint,
    id_sucursal bigint,
    id_tienda bigint,
    id_cuenta_costo bigint,
    descripcion character varying(300),
    cantidad numeric(18,6) NOT NULL DEFAULT 1,
    costo_unitario numeric(18,6) NOT NULL DEFAULT 0,
    monto_subtotal numeric(18,6) NOT NULL DEFAULT 0,
    porcentaje_impuesto numeric(9,6) NOT NULL DEFAULT 0,
    monto_impuesto numeric(18,6) NOT NULL DEFAULT 0,
    monto_total numeric(18,6) NOT NULL DEFAULT 0,
    moneda character varying(3) NOT NULL DEFAULT 'BOB',
    observaciones text,
    estado_registro character varying(20) DEFAULT 'Activo'::character varying,
    fecha_registro timestamp with time zone DEFAULT now(),
    fecha_modificacion timestamp with time zone,
    version_registro integer DEFAULT 1,
    id_usuario_creador bigint,
    id_usuario_modificacion bigint,
    CONSTRAINT ck_transaccion_detalle_costo_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_transaccion_detalle_costo_costo CHECK (costo_unitario >= 0),
    CONSTRAINT ck_transaccion_detalle_costo_impuesto CHECK (porcentaje_impuesto >= 0 AND porcentaje_impuesto <= 100),
    CONSTRAINT ck_transaccion_detalle_costo_montos CHECK (
      monto_subtotal >= 0 AND monto_impuesto >= 0 AND monto_total >= 0
    ),
    CONSTRAINT ck_transaccion_detalle_costo_referencia CHECK (
      id_concepto_costo IS NOT NULL
      OR id_bien IS NOT NULL
      OR id_movimiento_detalle IS NOT NULL
      OR id_empleado IS NOT NULL
      OR id_departamento IS NOT NULL
      OR descripcion IS NOT NULL
    )
);

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_transaccion_fkey
  FOREIGN KEY (id_transaccion) REFERENCES contabilidad.transaccion(id_transaccion) ON DELETE CASCADE;

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_cliente_fkey
  FOREIGN KEY (id_cliente) REFERENCES persona.persona(id_persona);

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_producto_educativo_fkey
  FOREIGN KEY (id_producto_educativo) REFERENCES servicios_educativos.producto_educativo(id_producto_educativo);

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_producto_tienda_fkey
  FOREIGN KEY (id_producto_tienda) REFERENCES inventario.bien(id_bien);

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_curso_version_fkey
  FOREIGN KEY (id_curso_version) REFERENCES servicios_educativos.curso_version(id_curso_version);

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_clase_por_hora_fkey
  FOREIGN KEY (id_clase_por_hora) REFERENCES servicios_educativos.clase_por_hora(id_clase);

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_tienda_fkey
  FOREIGN KEY (id_tienda) REFERENCES infraestructura.tienda(id_tienda);

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_sucursal_fkey
  FOREIGN KEY (id_sucursal) REFERENCES infraestructura.sucursal(id_sucursal);

ALTER TABLE contabilidad.transaccion_detalle_venta
  ADD CONSTRAINT transaccion_detalle_venta_id_cuenta_ingreso_fkey
  FOREIGN KEY (id_cuenta_ingreso) REFERENCES contabilidad.cuenta(id_cuenta);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_transaccion_fkey
  FOREIGN KEY (id_transaccion) REFERENCES contabilidad.transaccion(id_transaccion) ON DELETE CASCADE;

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_centro_costo_fkey
  FOREIGN KEY (id_centro_costo) REFERENCES contabilidad.centro_costo(id_centro_costo);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_concepto_costo_fkey
  FOREIGN KEY (id_concepto_costo) REFERENCES contabilidad.concepto_costo(id_concepto);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_centro_costo_mapa_fkey
  FOREIGN KEY (id_centro_costo_mapa) REFERENCES contabilidad.centro_costo_mapa(id_cc_mapa);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_proveedor_fkey
  FOREIGN KEY (id_proveedor) REFERENCES persona.proveedor(id_proveedor);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_empleado_fkey
  FOREIGN KEY (id_empleado) REFERENCES administracion.empleado(id_empleado);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_departamento_fkey
  FOREIGN KEY (id_departamento) REFERENCES administracion.departamento(id_departamento);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_bien_fkey
  FOREIGN KEY (id_bien) REFERENCES inventario.bien(id_bien);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_movimiento_detalle_fkey
  FOREIGN KEY (id_movimiento_detalle) REFERENCES inventario.movimiento_detalle(id_movimiento);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_sucursal_fkey
  FOREIGN KEY (id_sucursal) REFERENCES infraestructura.sucursal(id_sucursal);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_tienda_fkey
  FOREIGN KEY (id_tienda) REFERENCES infraestructura.tienda(id_tienda);

ALTER TABLE contabilidad.transaccion_detalle_costo
  ADD CONSTRAINT transaccion_detalle_costo_id_cuenta_costo_fkey
  FOREIGN KEY (id_cuenta_costo) REFERENCES contabilidad.cuenta(id_cuenta);

CREATE UNIQUE INDEX IF NOT EXISTS ux_transaccion_detalle_venta_linea
  ON contabilidad.transaccion_detalle_venta (id_transaccion, numero_linea);

CREATE UNIQUE INDEX IF NOT EXISTS ux_transaccion_detalle_costo_linea
  ON contabilidad.transaccion_detalle_costo (id_transaccion, numero_linea);

CREATE INDEX IF NOT EXISTS ix_transaccion_detalle_venta_transaccion
  ON contabilidad.transaccion_detalle_venta (id_transaccion);

CREATE INDEX IF NOT EXISTS ix_transaccion_detalle_venta_producto_educativo
  ON contabilidad.transaccion_detalle_venta (id_producto_educativo);

CREATE INDEX IF NOT EXISTS ix_transaccion_detalle_venta_producto_tienda
  ON contabilidad.transaccion_detalle_venta (id_producto_tienda);

CREATE INDEX IF NOT EXISTS ix_transaccion_detalle_venta_cliente
  ON contabilidad.transaccion_detalle_venta (id_cliente);

CREATE INDEX IF NOT EXISTS ix_transaccion_detalle_costo_transaccion
  ON contabilidad.transaccion_detalle_costo (id_transaccion);

CREATE INDEX IF NOT EXISTS ix_transaccion_detalle_costo_centro_costo
  ON contabilidad.transaccion_detalle_costo (id_centro_costo);

CREATE INDEX IF NOT EXISTS ix_transaccion_detalle_costo_concepto
  ON contabilidad.transaccion_detalle_costo (id_concepto_costo);

CREATE INDEX IF NOT EXISTS ix_transaccion_detalle_costo_bien
  ON contabilidad.transaccion_detalle_costo (id_bien);


CREATE OR REPLACE FUNCTION contabilidad.fn_calcular_transaccion_detalle_venta_totales()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  bruto numeric(18,6);
  descuento_porcentaje numeric(18,6);
  descuento_final numeric(18,6);
  subtotal_final numeric(18,6);
  impuesto_final numeric(18,6);
BEGIN
  bruto := COALESCE(NEW.cantidad, 0) * COALESCE(NEW.precio_unitario, 0);
  descuento_porcentaje := bruto * COALESCE(NEW.porcentaje_descuento, 0) / 100;
  descuento_final := GREATEST(COALESCE(NEW.monto_descuento, 0), descuento_porcentaje);
  subtotal_final := GREATEST(bruto - descuento_final, 0);

  IF COALESCE(NEW.monto_impuesto, 0) > 0 THEN
    impuesto_final := COALESCE(NEW.monto_impuesto, 0);
  ELSE
    impuesto_final := subtotal_final * COALESCE(NEW.porcentaje_impuesto, 0) / 100;
  END IF;

  NEW.monto_descuento := descuento_final;
  NEW.monto_subtotal := subtotal_final;
  NEW.monto_impuesto := impuesto_final;
  NEW.monto_total := subtotal_final + impuesto_final;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION contabilidad.fn_calcular_transaccion_detalle_costo_totales()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  subtotal_final numeric(18,6);
  impuesto_final numeric(18,6);
BEGIN
  subtotal_final := COALESCE(NEW.cantidad, 0) * COALESCE(NEW.costo_unitario, 0);

  IF COALESCE(NEW.monto_impuesto, 0) > 0 THEN
    impuesto_final := COALESCE(NEW.monto_impuesto, 0);
  ELSE
    impuesto_final := subtotal_final * COALESCE(NEW.porcentaje_impuesto, 0) / 100;
  END IF;

  NEW.monto_subtotal := subtotal_final;
  NEW.monto_impuesto := impuesto_final;
  NEW.monto_total := subtotal_final + impuesto_final;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_calcular_transaccion_detalle_venta_totales
  BEFORE INSERT OR UPDATE
  ON contabilidad.transaccion_detalle_venta
  FOR EACH ROW
  EXECUTE FUNCTION contabilidad.fn_calcular_transaccion_detalle_venta_totales();

CREATE TRIGGER trg_calcular_transaccion_detalle_costo_totales
  BEFORE INSERT OR UPDATE
  ON contabilidad.transaccion_detalle_costo
  FOR EACH ROW
  EXECUTE FUNCTION contabilidad.fn_calcular_transaccion_detalle_costo_totales();

CREATE OR REPLACE FUNCTION contabilidad.fn_validar_detalle_transaccion_tipo()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  tipo_esperado text := TG_ARGV[0];
  tipo_actual text;
BEGIN
  SELECT t.tipo_transaccion::text
    INTO tipo_actual
  FROM contabilidad.transaccion t
  WHERE t.id_transaccion = NEW.id_transaccion;

  IF tipo_actual IS NULL THEN
    RAISE EXCEPTION 'No existe la transacción % para registrar el detalle.', NEW.id_transaccion;
  END IF;

  IF tipo_actual <> tipo_esperado THEN
    RAISE EXCEPTION 'La tabla % solo acepta transacciones tipo %, pero recibió tipo %.', TG_TABLE_NAME, tipo_esperado, tipo_actual;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_transaccion_detalle_venta_tipo
  BEFORE INSERT OR UPDATE OF id_transaccion
  ON contabilidad.transaccion_detalle_venta
  FOR EACH ROW
  EXECUTE FUNCTION contabilidad.fn_validar_detalle_transaccion_tipo('VENTA');

CREATE TRIGGER trg_transaccion_detalle_costo_tipo
  BEFORE INSERT OR UPDATE OF id_transaccion
  ON contabilidad.transaccion_detalle_costo
  FOR EACH ROW
  EXECUTE FUNCTION contabilidad.fn_validar_detalle_transaccion_tipo('COSTO');

CREATE TRIGGER bu_transaccion_detalle_venta
  BEFORE UPDATE ON contabilidad.transaccion_detalle_venta
  FOR EACH ROW EXECUTE FUNCTION contabilidad.fn_audit_bu_simple();

CREATE TRIGGER bu_transaccion_detalle_costo
  BEFORE UPDATE ON contabilidad.transaccion_detalle_costo
  FOR EACH ROW EXECUTE FUNCTION contabilidad.fn_audit_bu_simple();

CREATE OR REPLACE VIEW contabilidad.v_transaccion_detalle_venta AS
SELECT
  dv.*,
  t.fecha_transaccion,
  t.tipo_transaccion,
  t.glosa,
  pe.nombre AS producto_educativo_nombre,
  b.nombre AS producto_tienda_nombre,
  cli.nombres AS cliente_nombres,
  cli.apellidos AS cliente_apellidos,
  ci.codigo AS cuenta_ingreso_codigo,
  ci.nombre_cuenta AS cuenta_ingreso_nombre
FROM contabilidad.transaccion_detalle_venta dv
JOIN contabilidad.transaccion t ON t.id_transaccion = dv.id_transaccion
LEFT JOIN servicios_educativos.producto_educativo pe ON pe.id_producto_educativo = dv.id_producto_educativo
LEFT JOIN inventario.bien b ON b.id_bien = dv.id_producto_tienda
LEFT JOIN persona.persona cli ON cli.id_persona = dv.id_cliente
LEFT JOIN contabilidad.cuenta ci ON ci.id_cuenta = dv.id_cuenta_ingreso
WHERE dv.estado_registro = 'Activo';

CREATE OR REPLACE VIEW contabilidad.v_transaccion_detalle_costo AS
SELECT
  dc.*,
  t.fecha_transaccion,
  t.tipo_transaccion,
  t.glosa,
  cc.codigo AS centro_costo_codigo,
  cc.nombre AS centro_costo_nombre,
  cco.codigo AS concepto_costo_codigo,
  cco.nombre AS concepto_costo_nombre,
  p.nombre_proveedor,
  b.nombre AS bien_nombre,
  ccu.codigo AS cuenta_costo_codigo,
  ccu.nombre_cuenta AS cuenta_costo_nombre
FROM contabilidad.transaccion_detalle_costo dc
JOIN contabilidad.transaccion t ON t.id_transaccion = dc.id_transaccion
LEFT JOIN contabilidad.centro_costo cc ON cc.id_centro_costo = dc.id_centro_costo
LEFT JOIN contabilidad.concepto_costo cco ON cco.id_concepto = dc.id_concepto_costo
LEFT JOIN persona.proveedor p ON p.id_proveedor = dc.id_proveedor
LEFT JOIN inventario.bien b ON b.id_bien = dc.id_bien
LEFT JOIN contabilidad.cuenta ccu ON ccu.id_cuenta = dc.id_cuenta_costo
WHERE dc.estado_registro = 'Activo';

INSERT INTO seguridad.permiso (codigo, descripcion, modulo)
VALUES
  ('CONTABILIDAD.TRANSACCION_DETALLE_VENTA.CREATE', 'Crear detalle de transacción de venta', 'CONTABILIDAD'),
  ('CONTABILIDAD.TRANSACCION_DETALLE_VENTA.READ', 'Leer detalle de transacción de venta', 'CONTABILIDAD'),
  ('CONTABILIDAD.TRANSACCION_DETALLE_VENTA.UPDATE', 'Actualizar detalle de transacción de venta', 'CONTABILIDAD'),
  ('CONTABILIDAD.TRANSACCION_DETALLE_COSTO.CREATE', 'Crear detalle de transacción de costo', 'CONTABILIDAD'),
  ('CONTABILIDAD.TRANSACCION_DETALLE_COSTO.READ', 'Leer detalle de transacción de costo', 'CONTABILIDAD'),
  ('CONTABILIDAD.TRANSACCION_DETALLE_COSTO.UPDATE', 'Actualizar detalle de transacción de costo', 'CONTABILIDAD')
ON CONFLICT (codigo) DO UPDATE
SET descripcion = EXCLUDED.descripcion,
    modulo = EXCLUDED.modulo,
    estado_registro = 'Activo';

INSERT INTO seguridad.rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM seguridad.rol r
JOIN seguridad.permiso p ON p.codigo = ANY(ARRAY[
  'CONTABILIDAD.TRANSACCION_DETALLE_VENTA.CREATE',
  'CONTABILIDAD.TRANSACCION_DETALLE_VENTA.READ',
  'CONTABILIDAD.TRANSACCION_DETALLE_VENTA.UPDATE',
  'CONTABILIDAD.TRANSACCION_DETALLE_COSTO.CREATE',
  'CONTABILIDAD.TRANSACCION_DETALLE_COSTO.READ',
  'CONTABILIDAD.TRANSACCION_DETALLE_COSTO.UPDATE'
])
WHERE r.codigo IN ('SUPER_ADMIN', 'ADMIN_GENERAL', 'CONTADOR_GENERAL', 'CONTADOR')
ON CONFLICT (id_rol, id_permiso) DO NOTHING;
