-- 005_patch_venta_clase_registro_endpoint.sql
-- Patch operativo-contable: Parte de clases pasadas -> venta + detalle + asiento contable.
-- Crea tabla de trazabilidad para guardar la fila original capturada por frontend.
-- El endpoint NestJS que usa esta tabla es:
--   POST /api/contabilidad/venta-clase/registrar
--   POST /api/contabilidad/venta-clase/registrar-batch

CREATE TABLE IF NOT EXISTS contabilidad.venta_clase_registro (
    id_venta_clase_registro bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date NOT NULL,
    hora_ingreso time without time zone,
    hora_salida time without time zone,
    id_estudiante bigint,
    estudiante_texto character varying(220),
    id_tutor bigint,
    tutor_texto character varying(220),
    id_aula bigint,
    id_materia_tree bigint,
    id_producto_educativo bigint,
    id_curso_version bigint,
    id_sucursal bigint,
    id_tienda bigint,
    motivo_clase text,
    materia_texto character varying(160),
    tema character varying(180),
    subtema character varying(180),
    monto_efectivo numeric(18,6) NOT NULL DEFAULT 0,
    monto_qr numeric(18,6) NOT NULL DEFAULT 0,
    monto_cxc numeric(18,6) NOT NULL DEFAULT 0,
    monto_paquete numeric(18,6) NOT NULL DEFAULT 0,
    monto_total numeric(18,6) NOT NULL DEFAULT 0,
    situacion_base character varying(80) NOT NULL DEFAULT 'CLASE_PASADA',
    observaciones text,
    id_clase_por_hora bigint,
    id_transaccion bigint,
    id_detalle_venta bigint,
    estado_proceso character varying(30) NOT NULL DEFAULT 'REGISTRADO',
    advertencias jsonb NOT NULL DEFAULT '[]'::jsonb,
    payload_original jsonb,
    estado_registro character varying(20) DEFAULT 'Activo'::character varying,
    fecha_registro timestamp with time zone DEFAULT now(),
    fecha_modificacion timestamp with time zone,
    version_registro integer DEFAULT 1,
    id_usuario_creador bigint,
    id_usuario_modificacion bigint,
    CONSTRAINT ck_venta_clase_registro_montos CHECK (
      monto_efectivo >= 0 AND monto_qr >= 0 AND monto_cxc >= 0 AND monto_paquete >= 0 AND monto_total >= 0
    ),
    CONSTRAINT ck_venta_clase_registro_monto_positivo CHECK (
      monto_total > 0 OR monto_efectivo > 0 OR monto_qr > 0 OR monto_cxc > 0 OR monto_paquete > 0
    )
);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_estudiante_fkey
  FOREIGN KEY (id_estudiante) REFERENCES persona.persona_estudiante(id_persona);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_tutor_fkey
  FOREIGN KEY (id_tutor) REFERENCES persona.persona_tutor(id_tutor);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_aula_fkey
  FOREIGN KEY (id_aula) REFERENCES infraestructura.espacio(id_espacio);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_materia_tree_fkey
  FOREIGN KEY (id_materia_tree) REFERENCES servicios_educativos.materia_tree(id_tree);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_producto_educativo_fkey
  FOREIGN KEY (id_producto_educativo) REFERENCES servicios_educativos.producto_educativo(id_producto_educativo);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_curso_version_fkey
  FOREIGN KEY (id_curso_version) REFERENCES servicios_educativos.curso_version(id_curso_version);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_sucursal_fkey
  FOREIGN KEY (id_sucursal) REFERENCES infraestructura.sucursal(id_sucursal);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_tienda_fkey
  FOREIGN KEY (id_tienda) REFERENCES infraestructura.tienda(id_tienda);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_clase_por_hora_fkey
  FOREIGN KEY (id_clase_por_hora) REFERENCES servicios_educativos.clase_por_hora(id_clase);

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_transaccion_fkey
  FOREIGN KEY (id_transaccion) REFERENCES contabilidad.transaccion(id_transaccion) ON DELETE SET NULL;

ALTER TABLE contabilidad.venta_clase_registro
  ADD CONSTRAINT venta_clase_registro_id_detalle_venta_fkey
  FOREIGN KEY (id_detalle_venta) REFERENCES contabilidad.transaccion_detalle_venta(id_detalle_venta) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_venta_clase_registro_fecha
  ON contabilidad.venta_clase_registro (fecha);

CREATE INDEX IF NOT EXISTS ix_venta_clase_registro_estudiante
  ON contabilidad.venta_clase_registro (id_estudiante);

CREATE INDEX IF NOT EXISTS ix_venta_clase_registro_tutor
  ON contabilidad.venta_clase_registro (id_tutor);

CREATE INDEX IF NOT EXISTS ix_venta_clase_registro_transaccion
  ON contabilidad.venta_clase_registro (id_transaccion);

CREATE INDEX IF NOT EXISTS ix_venta_clase_registro_estado
  ON contabilidad.venta_clase_registro (estado_registro, estado_proceso);

CREATE TRIGGER bu_venta_clase_registro
  BEFORE UPDATE ON contabilidad.venta_clase_registro
  FOR EACH ROW EXECUTE FUNCTION contabilidad.fn_audit_bu_simple();

CREATE OR REPLACE VIEW contabilidad.v_venta_clase_registro AS
SELECT
  vcr.*,
  CONCAT_WS(' ', est.nombres, est.apellidos) AS estudiante_nombre_completo,
  CONCAT_WS(' ', per_tutor.nombres, per_tutor.apellidos) AS tutor_nombre_completo,
  mt.nombre AS materia_nombre,
  mt.tema AS materia_tema,
  mt.subtema AS materia_subtema,
  pe.nombre AS producto_educativo_nombre,
  cv.nombre_version AS curso_version_nombre,
  t.tipo_transaccion,
  t.glosa AS transaccion_glosa,
  dv.monto_subtotal AS detalle_monto_subtotal,
  dv.monto_impuesto AS detalle_monto_impuesto,
  dv.monto_total AS detalle_monto_total
FROM contabilidad.venta_clase_registro vcr
LEFT JOIN persona.persona est ON est.id_persona = vcr.id_estudiante
LEFT JOIN persona.persona_tutor tutor ON tutor.id_tutor = vcr.id_tutor
LEFT JOIN persona.persona per_tutor ON per_tutor.id_persona = tutor.id_persona
LEFT JOIN servicios_educativos.materia_tree mt ON mt.id_tree = vcr.id_materia_tree
LEFT JOIN servicios_educativos.producto_educativo pe ON pe.id_producto_educativo = vcr.id_producto_educativo
LEFT JOIN servicios_educativos.curso_version cv ON cv.id_curso_version = vcr.id_curso_version
LEFT JOIN contabilidad.transaccion t ON t.id_transaccion = vcr.id_transaccion
LEFT JOIN contabilidad.transaccion_detalle_venta dv ON dv.id_detalle_venta = vcr.id_detalle_venta
WHERE COALESCE(vcr.estado_registro, 'Activo') = 'Activo';

INSERT INTO seguridad.permiso (codigo, descripcion, modulo)
VALUES
  ('CONTABILIDAD.VENTA_CLASE.REGISTRAR', 'Registrar parte de clases pasadas como venta contable completa', 'CONTABILIDAD'),
  ('CONTABILIDAD.VENTA_CLASE_REGISTRO.CREATE', 'Crear registro de parte de clases pasadas', 'CONTABILIDAD'),
  ('CONTABILIDAD.VENTA_CLASE_REGISTRO.READ', 'Leer registros de parte de clases pasadas', 'CONTABILIDAD'),
  ('CONTABILIDAD.VENTA_CLASE_REGISTRO.UPDATE', 'Actualizar registros de parte de clases pasadas', 'CONTABILIDAD')
ON CONFLICT (codigo) DO UPDATE
SET descripcion = EXCLUDED.descripcion,
    modulo = EXCLUDED.modulo,
    estado_registro = 'Activo';

INSERT INTO seguridad.rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM seguridad.rol r
JOIN seguridad.permiso p ON p.codigo = ANY(ARRAY[
  'CONTABILIDAD.VENTA_CLASE.REGISTRAR',
  'CONTABILIDAD.VENTA_CLASE_REGISTRO.CREATE',
  'CONTABILIDAD.VENTA_CLASE_REGISTRO.READ',
  'CONTABILIDAD.VENTA_CLASE_REGISTRO.UPDATE'
])
WHERE r.codigo IN ('SUPER_ADMIN', 'ADMIN_GENERAL', 'CONTADOR_GENERAL', 'CONTADOR')
ON CONFLICT (id_rol, id_permiso) DO NOTHING;
