-- 006_patch_cuentas_operativas_por_persona.sql
-- Propósito:
--  1) Configurar manualmente cuentas operativas globales para efectivo, QR, IVA e ingreso de clases.
--  2) Crear cuentas contables asociadas a cada estudiante para CxC y paquetes/ingresos diferidos.
--  3) Crear cuenta por pagar asociada a cada tutor.
--  4) Dejar endpoints CRUD/batch para configurar las cuentas operativas desde el frontend.

CREATE TABLE IF NOT EXISTS contabilidad.configuracion_cuenta_operativa (
    id_configuracion_cuenta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE,
    nombre text NOT NULL,
    descripcion text,
    id_cuenta bigint NOT NULL REFERENCES contabilidad.cuenta(id_cuenta),
    es_obligatoria boolean DEFAULT true NOT NULL,
    estado_registro character varying(20) DEFAULT 'Activo'::character varying,
    fecha_registro timestamp with time zone DEFAULT now(),
    fecha_modificacion timestamp with time zone,
    version_registro integer DEFAULT 1,
    id_usuario_creador bigint,
    id_usuario_modificacion bigint
);

CREATE INDEX IF NOT EXISTS ix_configuracion_cuenta_operativa_estado
  ON contabilidad.configuracion_cuenta_operativa (estado_registro);

-- Función de auditoría mínima requerida por esta migración.
-- No estaba presente en el schema base 001, por eso fresh fallaba en 006.
CREATE OR REPLACE FUNCTION seguridad.fn_set_audit_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.fecha_modificacion := now();
  NEW.version_registro := COALESCE(OLD.version_registro, NEW.version_registro, 1) + 1;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS bu_configuracion_cuenta_operativa ON contabilidad.configuracion_cuenta_operativa;

CREATE TRIGGER bu_configuracion_cuenta_operativa
  BEFORE UPDATE ON contabilidad.configuracion_cuenta_operativa
  FOR EACH ROW EXECUTE FUNCTION seguridad.fn_set_audit_update();

INSERT INTO contabilidad.configuracion_cuenta_operativa (codigo, nombre, descripcion, id_cuenta)
SELECT cfg.codigo, cfg.nombre, cfg.descripcion, c.id_cuenta
FROM (VALUES
  ('CANAL_COBRO_EFECTIVO', 'Cuenta de cobro en efectivo', 'Cuenta contable usada por defecto cuando una venta-clase se cobra en efectivo.', '1.1.01.001'),
  ('CANAL_COBRO_QR', 'Cuenta de cobro por QR', 'Cuenta contable usada por defecto cuando una venta-clase se cobra por QR/pago móvil.', '1.1.01.013'),
  ('IVA_DEBITO_FISCAL', 'IVA débito fiscal', 'Cuenta contable usada cuando la venta-clase incluye impuesto.', '2.1.05.001'),
  ('INGRESO_CLASE_POR_HORA', 'Ingreso por clases por hora', 'Cuenta de ingreso usada por defecto para clases por hora.', '4.1.01.001')
) AS cfg(codigo, nombre, descripcion, codigo_cuenta)
JOIN contabilidad.cuenta c ON c.codigo = cfg.codigo_cuenta
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    id_cuenta = EXCLUDED.id_cuenta,
    estado_registro = 'Activo';

-- Backfill: cuentas CxC y paquete diferido por estudiante existente.
WITH estudiantes AS (
  SELECT pe.id_persona,
         COALESCE(NULLIF(TRIM(CONCAT_WS(' ', p.nombres, p.apellidos)), ''), 'Estudiante ' || pe.id_persona::text) AS nombre_completo
  FROM persona.persona_estudiante pe
  LEFT JOIN persona.persona p ON p.id_persona = pe.id_persona
), grupo_cxc AS (
  SELECT id_grupo_cuenta FROM contabilidad.grupo_cuenta WHERE codigo = '1.1.03' LIMIT 1
), grupo_paq AS (
  SELECT id_grupo_cuenta FROM contabilidad.grupo_cuenta WHERE codigo = '2.1.06' LIMIT 1
), cuentas_cxc AS (
  INSERT INTO contabilidad.cuenta (codigo, nombre_cuenta, id_grupo_cuenta, estado_registro)
  SELECT '1.1.03.E' || e.id_persona::text,
         LEFT('CxC estudiante ' || e.id_persona::text || ' - ' || e.nombre_completo, 180),
         gc.id_grupo_cuenta,
         'Activo'
  FROM estudiantes e
  CROSS JOIN grupo_cxc gc
  ON CONFLICT (codigo) DO UPDATE
  SET nombre_cuenta = EXCLUDED.nombre_cuenta,
      estado_registro = 'Activo'
  RETURNING id_cuenta, codigo
)
INSERT INTO contabilidad.cuenta_asignacion (entidad_tipo, id_persona_estudiante, id_cuenta, prioridad, vigente_desde, estado_registro)
SELECT 'ESTUDIANTE_CXC',
       split_part(c.codigo, 'E', 2)::bigint,
       c.id_cuenta,
       1,
       CURRENT_DATE,
       'Activo'
FROM cuentas_cxc c
WHERE NOT EXISTS (
  SELECT 1
  FROM contabilidad.cuenta_asignacion ca
  WHERE ca.entidad_tipo = 'ESTUDIANTE_CXC'
    AND ca.id_persona_estudiante = split_part(c.codigo, 'E', 2)::bigint
    AND COALESCE(ca.estado_registro, 'Activo') IN ('Activo', 'ACTIVO', 'activo')
);

WITH estudiantes AS (
  SELECT pe.id_persona,
         COALESCE(NULLIF(TRIM(CONCAT_WS(' ', p.nombres, p.apellidos)), ''), 'Estudiante ' || pe.id_persona::text) AS nombre_completo
  FROM persona.persona_estudiante pe
  LEFT JOIN persona.persona p ON p.id_persona = pe.id_persona
), grupo_paq AS (
  SELECT id_grupo_cuenta FROM contabilidad.grupo_cuenta WHERE codigo = '2.1.06' LIMIT 1
), cuentas_paq AS (
  INSERT INTO contabilidad.cuenta (codigo, nombre_cuenta, id_grupo_cuenta, estado_registro)
  SELECT '2.1.06.E' || e.id_persona::text,
         LEFT('Paquetes cobrados por anticipado estudiante ' || e.id_persona::text || ' - ' || e.nombre_completo, 180),
         gp.id_grupo_cuenta,
         'Activo'
  FROM estudiantes e
  CROSS JOIN grupo_paq gp
  ON CONFLICT (codigo) DO UPDATE
  SET nombre_cuenta = EXCLUDED.nombre_cuenta,
      estado_registro = 'Activo'
  RETURNING id_cuenta, codigo
)
INSERT INTO contabilidad.cuenta_asignacion (entidad_tipo, id_persona_estudiante, id_cuenta, prioridad, vigente_desde, estado_registro)
SELECT 'ESTUDIANTE_PAQUETE_DIFERIDO',
       split_part(c.codigo, 'E', 2)::bigint,
       c.id_cuenta,
       1,
       CURRENT_DATE,
       'Activo'
FROM cuentas_paq c
WHERE NOT EXISTS (
  SELECT 1
  FROM contabilidad.cuenta_asignacion ca
  WHERE ca.entidad_tipo = 'ESTUDIANTE_PAQUETE_DIFERIDO'
    AND ca.id_persona_estudiante = split_part(c.codigo, 'E', 2)::bigint
    AND COALESCE(ca.estado_registro, 'Activo') IN ('Activo', 'ACTIVO', 'activo')
);

-- Backfill: CxP por tutor existente.
WITH tutores AS (
  SELECT pt.id_tutor,
         COALESCE(NULLIF(TRIM(CONCAT_WS(' ', p.nombres, p.apellidos)), ''), 'Tutor ' || pt.id_tutor::text) AS nombre_completo
  FROM persona.persona_tutor pt
  LEFT JOIN persona.persona p ON p.id_persona = pt.id_persona
), grupo_cxp AS (
  SELECT id_grupo_cuenta FROM contabilidad.grupo_cuenta WHERE codigo = '2.1.03' LIMIT 1
), cuentas_tutor AS (
  INSERT INTO contabilidad.cuenta (codigo, nombre_cuenta, id_grupo_cuenta, estado_registro)
  SELECT '2.1.03.T' || t.id_tutor::text,
         LEFT('CxP tutor ' || t.id_tutor::text || ' - ' || t.nombre_completo, 180),
         gc.id_grupo_cuenta,
         'Activo'
  FROM tutores t
  CROSS JOIN grupo_cxp gc
  ON CONFLICT (codigo) DO UPDATE
  SET nombre_cuenta = EXCLUDED.nombre_cuenta,
      estado_registro = 'Activo'
  RETURNING id_cuenta, codigo
)
INSERT INTO contabilidad.cuenta_asignacion (entidad_tipo, id_persona_tutor, id_cuenta, prioridad, vigente_desde, estado_registro)
SELECT 'TUTOR_CXP',
       split_part(c.codigo, 'T', 2)::bigint,
       c.id_cuenta,
       1,
       CURRENT_DATE,
       'Activo'
FROM cuentas_tutor c
WHERE NOT EXISTS (
  SELECT 1
  FROM contabilidad.cuenta_asignacion ca
  WHERE ca.entidad_tipo = 'TUTOR_CXP'
    AND ca.id_persona_tutor = split_part(c.codigo, 'T', 2)::bigint
    AND COALESCE(ca.estado_registro, 'Activo') IN ('Activo', 'ACTIVO', 'activo')
);

INSERT INTO seguridad.permiso (codigo, descripcion, modulo)
VALUES
  ('CONTABILIDAD.CONFIGURACION_CUENTA_OPERATIVA.CREATE', 'Crear configuración de cuentas operativas contables', 'CONTABILIDAD'),
  ('CONTABILIDAD.CONFIGURACION_CUENTA_OPERATIVA.READ', 'Leer configuración de cuentas operativas contables', 'CONTABILIDAD'),
  ('CONTABILIDAD.CONFIGURACION_CUENTA_OPERATIVA.UPDATE', 'Actualizar configuración de cuentas operativas contables', 'CONTABILIDAD')
ON CONFLICT (codigo) DO UPDATE
SET descripcion = EXCLUDED.descripcion,
    modulo = EXCLUDED.modulo,
    estado_registro = 'Activo';

INSERT INTO seguridad.rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM seguridad.rol r
JOIN seguridad.permiso p ON p.codigo = ANY(ARRAY[
  'CONTABILIDAD.CONFIGURACION_CUENTA_OPERATIVA.CREATE',
  'CONTABILIDAD.CONFIGURACION_CUENTA_OPERATIVA.READ',
  'CONTABILIDAD.CONFIGURACION_CUENTA_OPERATIVA.UPDATE'
])
WHERE r.codigo IN ('SUPER_ADMIN', 'ADMIN_GENERAL', 'CONTADOR_GENERAL', 'CONTADOR')
ON CONFLICT (id_rol, id_permiso) DO NOTHING;
