-- 007_seed_catalogos_academicos_scz.sql
-- Propósito:
--  1) Sembrar materia_tree para Matemáticas, Física y Química con temas y subtemas ampliados.
--  2) Sembrar unidades educativas principales de Santa Cruz de la Sierra: universidades y colegios.
--  3) Sembrar productos educativos base: clases de Matemáticas, Física, Química, curso de Becas CRE y otros cursos.
--
-- Idempotente: se puede ejecutar varias veces sin duplicar registros relevantes.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'materia_tree_nombre_key'
      AND conrelid = 'servicios_educativos.materia_tree'::regclass
  ) THEN
    ALTER TABLE servicios_educativos.materia_tree
      DROP CONSTRAINT materia_tree_nombre_key;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'uq_materia_tree_nombre_tema_subtema'
      AND conrelid = 'servicios_educativos.materia_tree'::regclass
  ) THEN
    ALTER TABLE servicios_educativos.materia_tree
      ADD CONSTRAINT uq_materia_tree_nombre_tema_subtema UNIQUE (nombre, tema, subtema);
  END IF;
END $$;

INSERT INTO servicios_educativos.materia_tree (
  nombre, tema, subtema, estado_registro, fecha_registro, fecha_modificacion, version_registro
)
SELECT v.nombre, v.tema, v.subtema, true, now(), now(), 1
FROM (VALUES
    ('Matemáticas', 'Aritmética', 'Operaciones con números reales'),
    ('Matemáticas', 'Aritmética', 'Fracciones, decimales y porcentajes'),
    ('Matemáticas', 'Aritmética', 'Razones y proporciones'),
    ('Matemáticas', 'Aritmética', 'Regla de tres simple y compuesta'),
    ('Matemáticas', 'Aritmética', 'Potenciación y radicación'),
    ('Matemáticas', 'Aritmética', 'Notación científica'),
    ('Matemáticas', 'Aritmética', 'Mínimo común múltiplo y máximo común divisor'),
    ('Matemáticas', 'Álgebra', 'Expresiones algebraicas'),
    ('Matemáticas', 'Álgebra', 'Productos notables'),
    ('Matemáticas', 'Álgebra', 'Factorización'),
    ('Matemáticas', 'Álgebra', 'Ecuaciones lineales'),
    ('Matemáticas', 'Álgebra', 'Ecuaciones cuadráticas'),
    ('Matemáticas', 'Álgebra', 'Sistemas de ecuaciones 2x2'),
    ('Matemáticas', 'Álgebra', 'Sistemas de ecuaciones 3x3'),
    ('Matemáticas', 'Álgebra', 'Inecuaciones lineales'),
    ('Matemáticas', 'Álgebra', 'Valor absoluto'),
    ('Matemáticas', 'Álgebra', 'Radicales algebraicos'),
    ('Matemáticas', 'Funciones', 'Plano cartesiano'),
    ('Matemáticas', 'Funciones', 'Dominio y rango'),
    ('Matemáticas', 'Funciones', 'Función lineal'),
    ('Matemáticas', 'Funciones', 'Función cuadrática'),
    ('Matemáticas', 'Funciones', 'Funciones exponenciales'),
    ('Matemáticas', 'Funciones', 'Funciones logarítmicas'),
    ('Matemáticas', 'Funciones', 'Composición de funciones'),
    ('Matemáticas', 'Funciones', 'Función inversa'),
    ('Matemáticas', 'Funciones', 'Transformaciones de funciones'),
    ('Matemáticas', 'Geometría', 'Ángulos y rectas'),
    ('Matemáticas', 'Geometría', 'Triángulos'),
    ('Matemáticas', 'Geometría', 'Teorema de Pitágoras'),
    ('Matemáticas', 'Geometría', 'Semejanza y congruencia'),
    ('Matemáticas', 'Geometría', 'Cuadriláteros y polígonos'),
    ('Matemáticas', 'Geometría', 'Circunferencia y círculo'),
    ('Matemáticas', 'Geometría', 'Áreas y perímetros'),
    ('Matemáticas', 'Geometría', 'Volúmenes de cuerpos geométricos'),
    ('Matemáticas', 'Geometría', 'Geometría analítica de la recta'),
    ('Matemáticas', 'Geometría', 'Distancia entre puntos'),
    ('Matemáticas', 'Trigonometría', 'Razones trigonométricas'),
    ('Matemáticas', 'Trigonometría', 'Ángulos notables'),
    ('Matemáticas', 'Trigonometría', 'Identidades trigonométricas básicas'),
    ('Matemáticas', 'Trigonometría', 'Resolución de triángulos'),
    ('Matemáticas', 'Trigonometría', 'Ley de senos'),
    ('Matemáticas', 'Trigonometría', 'Ley de cosenos'),
    ('Matemáticas', 'Trigonometría', 'Gráficas trigonométricas'),
    ('Matemáticas', 'Estadística', 'Media, mediana y moda'),
    ('Matemáticas', 'Estadística', 'Rango y desviación estándar'),
    ('Matemáticas', 'Estadística', 'Tablas de frecuencia'),
    ('Matemáticas', 'Estadística', 'Gráficos estadísticos'),
    ('Matemáticas', 'Estadística', 'Interpretación de datos'),
    ('Matemáticas', 'Estadística', 'Percentiles y cuartiles'),
    ('Matemáticas', 'Probabilidad', 'Probabilidad simple'),
    ('Matemáticas', 'Probabilidad', 'Probabilidad compuesta'),
    ('Matemáticas', 'Probabilidad', 'Principio multiplicativo'),
    ('Matemáticas', 'Probabilidad', 'Conteo y combinatoria básica'),
    ('Matemáticas', 'Probabilidad', 'Permutaciones y combinaciones'),
    ('Matemáticas', 'Probabilidad', 'Eventos independientes y dependientes'),
    ('Matemáticas', 'Razonamiento matemático', 'Series y sucesiones'),
    ('Matemáticas', 'Razonamiento matemático', 'Patrones numéricos'),
    ('Matemáticas', 'Razonamiento matemático', 'Problemas de edades'),
    ('Matemáticas', 'Razonamiento matemático', 'Problemas de móviles'),
    ('Matemáticas', 'Razonamiento matemático', 'Problemas de trabajo conjunto'),
    ('Matemáticas', 'Razonamiento matemático', 'Planteo de ecuaciones'),
    ('Matemáticas', 'Razonamiento matemático', 'Razonamiento lógico'),
    ('Matemáticas', 'Cálculo básico', 'Límites introductorios'),
    ('Matemáticas', 'Cálculo básico', 'Continuidad'),
    ('Matemáticas', 'Cálculo básico', 'Derivadas introductorias'),
    ('Matemáticas', 'Cálculo básico', 'Reglas básicas de derivación'),
    ('Matemáticas', 'Cálculo básico', 'Aplicaciones de la derivada'),
    ('Matemáticas', 'Cálculo básico', 'Integrales introductorias'),
    ('Física', 'Magnitudes y unidades', 'Sistema Internacional de Unidades'),
    ('Física', 'Magnitudes y unidades', 'Conversión de unidades'),
    ('Física', 'Magnitudes y unidades', 'Análisis dimensional'),
    ('Física', 'Magnitudes y unidades', 'Cifras significativas'),
    ('Física', 'Magnitudes y unidades', 'Notación científica aplicada'),
    ('Física', 'Vectores', 'Magnitudes escalares y vectoriales'),
    ('Física', 'Vectores', 'Suma de vectores'),
    ('Física', 'Vectores', 'Descomposición de vectores'),
    ('Física', 'Vectores', 'Producto escalar básico'),
    ('Física', 'Vectores', 'Vectores en el plano'),
    ('Física', 'Cinemática', 'Movimiento rectilíneo uniforme'),
    ('Física', 'Cinemática', 'Movimiento rectilíneo uniformemente variado'),
    ('Física', 'Cinemática', 'Caída libre'),
    ('Física', 'Cinemática', 'Movimiento parabólico'),
    ('Física', 'Cinemática', 'Movimiento circular uniforme'),
    ('Física', 'Cinemática', 'Gráficas posición-tiempo y velocidad-tiempo'),
    ('Física', 'Dinámica', 'Leyes de Newton'),
    ('Física', 'Dinámica', 'Diagramas de cuerpo libre'),
    ('Física', 'Dinámica', 'Fuerza de rozamiento'),
    ('Física', 'Dinámica', 'Plano inclinado'),
    ('Física', 'Dinámica', 'Tensión y poleas'),
    ('Física', 'Dinámica', 'Fuerza centrípeta'),
    ('Física', 'Trabajo y energía', 'Trabajo mecánico'),
    ('Física', 'Trabajo y energía', 'Potencia'),
    ('Física', 'Trabajo y energía', 'Energía cinética y potencial'),
    ('Física', 'Trabajo y energía', 'Conservación de la energía'),
    ('Física', 'Trabajo y energía', 'Energía mecánica con rozamiento'),
    ('Física', 'Cantidad de movimiento', 'Impulso y momentum'),
    ('Física', 'Cantidad de movimiento', 'Conservación del momentum'),
    ('Física', 'Cantidad de movimiento', 'Choques elásticos'),
    ('Física', 'Cantidad de movimiento', 'Choques inelásticos'),
    ('Física', 'Hidrostática', 'Densidad'),
    ('Física', 'Hidrostática', 'Presión'),
    ('Física', 'Hidrostática', 'Principio de Pascal'),
    ('Física', 'Hidrostática', 'Principio de Arquímedes'),
    ('Física', 'Hidrostática', 'Empuje y flotación'),
    ('Física', 'Termología', 'Temperatura y calor'),
    ('Física', 'Termología', 'Escalas termométricas'),
    ('Física', 'Termología', 'Calor específico'),
    ('Física', 'Termología', 'Cambios de estado'),
    ('Física', 'Termología', 'Dilatación térmica'),
    ('Física', 'Termología', 'Transferencia de calor'),
    ('Física', 'Electricidad', 'Carga eléctrica y ley de Coulomb'),
    ('Física', 'Electricidad', 'Campo eléctrico básico'),
    ('Física', 'Electricidad', 'Potencial eléctrico'),
    ('Física', 'Electricidad', 'Corriente y resistencia'),
    ('Física', 'Electricidad', 'Ley de Ohm'),
    ('Física', 'Electricidad', 'Circuitos eléctricos básicos'),
    ('Física', 'Electricidad', 'Potencia eléctrica'),
    ('Física', 'Ondas', 'Características de las ondas'),
    ('Física', 'Ondas', 'Frecuencia, periodo y longitud de onda'),
    ('Física', 'Ondas', 'Sonido'),
    ('Física', 'Ondas', 'Interferencia básica'),
    ('Física', 'Ondas', 'Ondas estacionarias introductorias'),
    ('Física', 'Óptica', 'Reflexión'),
    ('Física', 'Óptica', 'Refracción'),
    ('Física', 'Óptica', 'Espejos'),
    ('Física', 'Óptica', 'Lentes'),
    ('Física', 'Óptica', 'Formación de imágenes'),
    ('Química', 'Materia y medición', 'Propiedades de la materia'),
    ('Química', 'Materia y medición', 'Cambios físicos y químicos'),
    ('Química', 'Materia y medición', 'Estados de agregación'),
    ('Química', 'Materia y medición', 'Métodos de separación de mezclas'),
    ('Química', 'Materia y medición', 'Densidad y mediciones químicas'),
    ('Química', 'Estructura atómica', 'Partículas subatómicas'),
    ('Química', 'Estructura atómica', 'Número atómico y número másico'),
    ('Química', 'Estructura atómica', 'Isótopos'),
    ('Química', 'Estructura atómica', 'Configuración electrónica'),
    ('Química', 'Estructura atómica', 'Niveles y subniveles de energía'),
    ('Química', 'Tabla periódica', 'Grupos y periodos'),
    ('Química', 'Tabla periódica', 'Metales, no metales y metaloides'),
    ('Química', 'Tabla periódica', 'Propiedades periódicas'),
    ('Química', 'Tabla periódica', 'Electronegatividad'),
    ('Química', 'Tabla periódica', 'Radio atómico'),
    ('Química', 'Tabla periódica', 'Energía de ionización'),
    ('Química', 'Enlace químico', 'Enlace iónico'),
    ('Química', 'Enlace químico', 'Enlace covalente'),
    ('Química', 'Enlace químico', 'Enlace metálico'),
    ('Química', 'Enlace químico', 'Estructuras de Lewis'),
    ('Química', 'Enlace químico', 'Polaridad molecular'),
    ('Química', 'Enlace químico', 'Fuerzas intermoleculares'),
    ('Química', 'Nomenclatura inorgánica', 'Óxidos'),
    ('Química', 'Nomenclatura inorgánica', 'Hidróxidos'),
    ('Química', 'Nomenclatura inorgánica', 'Ácidos hidrácidos'),
    ('Química', 'Nomenclatura inorgánica', 'Ácidos oxácidos'),
    ('Química', 'Nomenclatura inorgánica', 'Sales binarias'),
    ('Química', 'Nomenclatura inorgánica', 'Oxisales'),
    ('Química', 'Nomenclatura inorgánica', 'Hidruros'),
    ('Química', 'Reacciones químicas', 'Tipos de reacciones'),
    ('Química', 'Reacciones químicas', 'Balanceo por tanteo'),
    ('Química', 'Reacciones químicas', 'Balanceo algebraico básico'),
    ('Química', 'Reacciones químicas', 'Reacciones redox introductorias'),
    ('Química', 'Reacciones químicas', 'Predicción de productos'),
    ('Química', 'Estequiometría', 'Mol y masa molar'),
    ('Química', 'Estequiometría', 'Número de Avogadro'),
    ('Química', 'Estequiometría', 'Relaciones mol-mol'),
    ('Química', 'Estequiometría', 'Relaciones masa-masa'),
    ('Química', 'Estequiometría', 'Reactivo limitante'),
    ('Química', 'Estequiometría', 'Rendimiento porcentual'),
    ('Química', 'Soluciones', 'Concentración molar'),
    ('Química', 'Soluciones', 'Porcentaje masa-volumen'),
    ('Química', 'Soluciones', 'Diluciones'),
    ('Química', 'Soluciones', 'Solubilidad'),
    ('Química', 'Soluciones', 'pH y pOH básicos'),
    ('Química', 'Gases', 'Ley de Boyle'),
    ('Química', 'Gases', 'Ley de Charles'),
    ('Química', 'Gases', 'Ley de Gay-Lussac'),
    ('Química', 'Gases', 'Ley de gases ideales'),
    ('Química', 'Gases', 'Condiciones normales'),
    ('Química', 'Química orgánica', 'Hidrocarburos básicos'),
    ('Química', 'Química orgánica', 'Alcanos, alquenos y alquinos'),
    ('Química', 'Química orgánica', 'Grupos funcionales básicos'),
    ('Química', 'Química orgánica', 'Alcoholes y ácidos carboxílicos'),
    ('Química', 'Química orgánica', 'Isomería introductoria')
) AS v(nombre, tema, subtema)
ON CONFLICT ON CONSTRAINT uq_materia_tree_nombre_tema_subtema
DO UPDATE SET
  estado_registro = true,
  fecha_modificacion = now(),
  version_registro = servicios_educativos.materia_tree.version_registro + 1;

INSERT INTO persona.unidad_educativa (nombre, categoria, estado_registro, fecha_registro, fecha_modificacion, version_registro)
SELECT v.nombre, v.categoria, true, now(), now(), 1
FROM (VALUES
    ('Universidad Autónoma Gabriel René Moreno (UAGRM)', 'fiscal'),
    ('Universidad Privada de Santa Cruz de la Sierra (UPSA)', 'privada'),
    ('Universidad Católica Boliviana San Pablo - Sede Santa Cruz', 'privada'),
    ('Universidad Tecnológica Privada de Santa Cruz (UTEPSA)', 'privada'),
    ('Universidad Privada Domingo Savio (UPDS)', 'privada'),
    ('Universidad de Aquino Bolivia (UDABOL) - Sede Santa Cruz', 'privada'),
    ('Universidad Franz Tamayo (UNIFRANZ) - Sede Santa Cruz', 'privada'),
    ('Universidad NUR', 'privada'),
    ('Universidad Evangélica Boliviana (UEB)', 'privada'),
    ('Universidad Nacional del Oriente (UNO)', 'privada'),
    ('Universidad Nacional Ecológica', 'privada'),
    ('Universidad Cristiana de Bolivia (UCEBOL)', 'privada'),
    ('Escuela Militar de Ingeniería (EMI) - Unidad Académica Santa Cruz', 'privada'),
    ('Universidad para el Desarrollo y la Innovación (UDI) - Santa Cruz', 'privada'),
    ('Universidad Privada Cumbre', 'privada'),
    ('Colegio Alemán Santa Cruz', 'privada'),
    ('Colegio Franco Boliviano Santa Cruz', 'privada'),
    ('Colegio La Salle Santa Cruz', 'convenio'),
    ('Colegio Marista Santa Cruz', 'privada'),
    ('Santa Cruz Cooperative School', 'privada'),
    ('Cambridge College Santa Cruz', 'privada'),
    ('Saint George School Santa Cruz', 'privada'),
    ('Saint Andrew School Santa Cruz', 'privada'),
    ('Colegio Panamericano Santa Cruz', 'privada'),
    ('Unidad Educativa Madre Vicenta Uboldi', 'privada'),
    ('Colegio María Goretti II', 'privada'),
    ('Colegio Parroquial de la Santa Cruz', 'convenio'),
    ('Colegio Domingo Savio Santa Cruz', 'privada'),
    ('Colegio Santa Ana Santa Cruz', 'privada'),
    ('Colegio San Agustín Santa Cruz', 'privada'),
    ('Colegio Espíritu Santo', 'privada'),
    ('Colegio Internacional de la Sierra', 'privada'),
    ('Colegio Isabel Saavedra', 'fiscal'),
    ('Colegio Británico Santa Cruz', 'privada'),
    ('Colegio Bilingüe Santa Cruz', 'privada'),
    ('Colegio Saint Thomas College', 'privada'),
    ('Colegio Católico Santa Cruz', 'convenio'),
    ('Colegio Evangélico Alfa y Omega', 'convenio'),
    ('Colegio Evangélico Henry Prince', 'privada'),
    ('Colegio Cristo Rey Santa Cruz', 'convenio'),
    ('Colegio Don Bosco Santa Cruz', 'convenio'),
    ('Colegio San Lorenzo Santa Cruz', 'convenio'),
    ('Colegio Sagrado Corazón Santa Cruz', 'privada'),
    ('Colegio Berea Santa Cruz', 'privada'),
    ('Colegio Montessori Santa Cruz', 'privada'),
    ('Colegio Eagles School Santa Cruz', 'privada'),
    ('Colegio Highlands Santa Cruz', 'privada'),
    ('Colegio San Jorge Santa Cruz', 'privada'),
    ('Colegio San Silvestre Santa Cruz', 'privada'),
    ('Colegio Uboldi Santa Cruz', 'privada'),
    ('Colegio Evangélico Bethesda', 'convenio'),
    ('Colegio Adventista Santa Cruz', 'convenio'),
    ('Colegio La Santa Cruz', 'convenio'),
    ('Colegio San Martín de Porres Santa Cruz', 'convenio'),
    ('Colegio María Auxiliadora Santa Cruz', 'convenio'),
    ('Colegio Nuestra Señora de Fátima Santa Cruz', 'convenio'),
    ('Colegio Santa Teresa Santa Cruz', 'privada'),
    ('Colegio Costa Rica', 'privada'),
    ('Colegio 1ro. de Mayo', 'privada'),
    ('Colegio Hallein Santa Teresa', 'privada'),
    ('Colegio Nacional Florida', 'fiscal'),
    ('Unidad Educativa Nacional Monseñor Santistevan', 'fiscal'),
    ('Unidad Educativa Elvira Parada', 'fiscal'),
    ('Unidad Educativa Santa Rosa de Lima', 'fiscal'),
    ('Unidad Educativa Humberto Vásquez Machicado', 'fiscal'),
    ('Unidad Educativa John Fitzgerald Kennedy', 'fiscal'),
    ('Unidad Educativa 6 de Junio', 'fiscal'),
    ('Unidad Educativa Vertino Candia Ayala', 'fiscal'),
    ('Unidad Educativa Sor María Cristina Pérez', 'fiscal'),
    ('Unidad Educativa Pedro Añez Pedraza', 'fiscal'),
    ('Unidad Educativa San Francisco de Asís Sur', 'fiscal'),
    ('Unidad Educativa Caritas', 'fiscal'),
    ('Unidad Educativa Hilandería Santa Cruz', 'fiscal'),
    ('Unidad Educativa Unión y Progreso', 'fiscal'),
    ('Unidad Educativa Oscar Arnulfo Romero', 'fiscal'),
    ('Unidad Educativa Efraín Vargas Paz', 'fiscal'),
    ('Unidad Educativa Julio Salmón', 'fiscal'),
    ('Unidad Educativa Alfredo Barbery Chávez', 'fiscal'),
    ('Unidad Educativa Germán Busch Santa Cruz', 'fiscal'),
    ('Unidad Educativa Enrique Finot', 'fiscal'),
    ('Unidad Educativa Cástulo Chávez', 'fiscal'),
    ('Unidad Educativa Juana Azurduy de Padilla', 'fiscal'),
    ('Unidad Educativa Melchor Pinto Parada', 'fiscal'),
    ('Unidad Educativa Nacional Ignacio Warnes', 'fiscal'),
    ('Unidad Educativa República Argentina', 'fiscal'),
    ('Unidad Educativa República del Brasil', 'fiscal'),
    ('Unidad Educativa Simón Bolívar Santa Cruz', 'fiscal'),
    ('Unidad Educativa Andrés Ibáñez', 'fiscal'),
    ('Unidad Educativa Carlos Aponte Tineo', 'fiscal'),
    ('Unidad Educativa José Malky', 'fiscal'),
    ('Unidad Educativa Santa Rosita', 'fiscal')
) AS v(nombre, categoria)
WHERE NOT EXISTS (
  SELECT 1
  FROM persona.unidad_educativa u
  WHERE lower(trim(u.nombre)) = lower(trim(v.nombre))
);

INSERT INTO servicios_educativos.producto_educativo (
  nombre,
  tipo_producto,
  descripcion,
  precio_base,
  lim_sup_estudiantes,
  lim_inf_estudiantes,
  estado_registro,
  fecha_registro,
  fecha_modificacion,
  version_registro
)
SELECT
  v.nombre,
  v.tipo_producto,
  v.descripcion,
  v.precio_base,
  v.lim_sup_estudiantes,
  v.lim_inf_estudiantes,
  true,
  now(),
  now(),
  1
FROM (VALUES
    ('Clase por hora', 'CLASE_POR_HORA', 'Servicio base de clase particular por hora para estudiantes.', 0, 1, 1),
    ('Clases de Matemáticas', 'CLASE_POR_HORA', 'Clases por hora de Matemáticas para colegio, preuniversitario, becas y nivelación.', 0, 1, 1),
    ('Clases de Física', 'CLASE_POR_HORA', 'Clases por hora de Física para colegio, preuniversitario, becas y nivelación.', 0, 1, 1),
    ('Clases de Química', 'CLASE_POR_HORA', 'Clases por hora de Química para colegio, preuniversitario, becas y nivelación.', 0, 1, 1),
    ('Clase por hora - Matemáticas', 'CLASE_POR_HORA', 'Clase particular por hora enfocada en Matemáticas.', 0, 1, 1),
    ('Clase por hora - Física', 'CLASE_POR_HORA', 'Clase particular por hora enfocada en Física.', 0, 1, 1),
    ('Clase por hora - Química', 'CLASE_POR_HORA', 'Clase particular por hora enfocada en Química.', 0, 1, 1),
    ('Curso de Becas CRE', 'CURSO', 'Curso de preparación para procesos de becas CRE.', 0, 30, 5),
    ('Curso de Becas CRE Intensivo', 'CURSO', 'Versión intensiva del curso de preparación para becas CRE.', 0, 30, 5),
    ('Curso de Becas CRE - Matemáticas', 'CURSO', 'Módulo de matemáticas para preparación de becas CRE.', 0, 30, 5),
    ('Curso de Becas CRE - Física', 'CURSO', 'Módulo de física para preparación de becas CRE.', 0, 30, 5),
    ('Curso de Becas CRE - Química', 'CURSO', 'Módulo de química para preparación de becas CRE.', 0, 30, 5),
    ('Curso de preparación UPSA', 'CURSO', 'Curso de preparación para admisión o nivelación orientada a UPSA.', 0, 30, 5),
    ('Curso de preparación UCB', 'CURSO', 'Curso de preparación para admisión o nivelación orientada a UCB.', 0, 30, 5),
    ('Curso preuniversitario UAGRM', 'CURSO', 'Curso de refuerzo preuniversitario orientado a la UAGRM.', 0, 35, 5),
    ('Curso de razonamiento matemático', 'CURSO', 'Curso de razonamiento matemático para pruebas de admisión y becas.', 0, 30, 5),
    ('Curso de física preuniversitaria', 'CURSO', 'Curso de física para nivelación y preparación preuniversitaria.', 0, 30, 5),
    ('Curso de química preuniversitaria', 'CURSO', 'Curso de química para nivelación y preparación preuniversitaria.', 0, 30, 5),
    ('Curso de nivelación escolar', 'CURSO', 'Curso de nivelación para estudiantes de secundaria.', 0, 25, 3),
    ('Curso de nivelación Matemáticas', 'CURSO', 'Nivelación escolar y preuniversitaria en Matemáticas.', 0, 25, 3),
    ('Curso de nivelación Física', 'CURSO', 'Nivelación escolar y preuniversitaria en Física.', 0, 25, 3),
    ('Curso de nivelación Química', 'CURSO', 'Nivelación escolar y preuniversitaria en Química.', 0, 25, 3),
    ('Taller de resolución de problemas', 'TALLER', 'Taller práctico para resolver ejercicios guiados por materia.', 0, 25, 3),
    ('Taller intensivo de Matemáticas', 'TALLER', 'Taller intensivo de ejercicios de Matemáticas.', 0, 25, 3),
    ('Taller intensivo de Física', 'TALLER', 'Taller intensivo de ejercicios de Física.', 0, 25, 3),
    ('Taller intensivo de Química', 'TALLER', 'Taller intensivo de ejercicios de Química.', 0, 25, 3),
    ('Simulacro de examen de becas', 'EVALUACION', 'Simulacro evaluativo para preparación de becas y admisión.', 0, 50, 1),
    ('Simulacro CRE completo', 'EVALUACION', 'Simulacro integral para preparación de becas CRE.', 0, 50, 1),
    ('Paquete de 10 horas de clase', 'PAQUETE_CLASES', 'Producto comercial para compra anticipada de 10 horas de clase.', 0, 1, 1),
    ('Paquete de 20 horas de clase', 'PAQUETE_CLASES', 'Producto comercial para compra anticipada de 20 horas de clase.', 0, 1, 1),
    ('Paquete de 40 horas de clase', 'PAQUETE_CLASES', 'Producto comercial para compra anticipada de 40 horas de clase.', 0, 1, 1)
) AS v(nombre, tipo_producto, descripcion, precio_base, lim_sup_estudiantes, lim_inf_estudiantes)
WHERE NOT EXISTS (
  SELECT 1
  FROM servicios_educativos.producto_educativo p
  WHERE lower(trim(p.nombre)) = lower(trim(v.nombre))
);

-- Ajuste de secuencias después de inserts manuales o migraciones previas.
SELECT setval('servicios_educativos.materia_tree_id_tree_seq', COALESCE((SELECT max(id_tree) FROM servicios_educativos.materia_tree), 1), true);
SELECT setval('persona.unidad_educativa_id_unidad_educativa_seq', COALESCE((SELECT max(id_unidad_educativa) FROM persona.unidad_educativa), 1), true);
SELECT setval('servicios_educativos.producto_educativo_id_producto_educativo_seq', COALESCE((SELECT max(id_producto_educativo) FROM servicios_educativos.producto_educativo), 1), true);
