-- 022_inscripcion_curso.sql
--
-- El esquema no tenía forma de decir "este estudiante cursa esta versión de
-- curso". Se podía registrar asistencia de cualquier estudiante a cualquier
-- clase, y ninguna pantalla podía proponer la lista correcta: la planilla de
-- asistencia terminaba ofreciendo TODOS los estudiantes del centro.
--
-- El único vínculo existente entre estudiante y curso es indirecto y contable:
-- `contabilidad.transaccion_venta.id_cliente` junto con `id_curso_version`. No
-- sirve como matrícula por dos motivos: `id_cliente` referencia a
-- `persona.persona` -puede ser el padre que paga, no el estudiante- y una venta
-- anulada o un pago adelantado no dicen nada sobre si el estudiante sigue en el
-- curso.
--
-- Esta migración crea la matrícula como lo que es: un hecho académico propio,
-- con su alta, su baja y su motivo. La venta sigue siendo la venta.
--
-- Idempotente: se puede ejecutar varias veces sin duplicar ni perder datos.

-- ---------------------------------------------------------------------------
-- 1) La tabla
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS servicios_educativos.inscripcion_curso (
    id_inscripcion      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_curso_version    bigint       NOT NULL,
    id_estudiante       bigint       NOT NULL,
    fecha_inscripcion   date         NOT NULL DEFAULT CURRENT_DATE,
    -- ACTIVA: cursa hoy. RETIRADA: se dio de baja. FINALIZADA: terminó el curso.
    -- Sólo las ACTIVA entran en la planilla de asistencia.
    estado              varchar(20)  NOT NULL DEFAULT 'ACTIVA',
    fecha_baja          date,
    motivo_baja         varchar(200),
    observaciones       varchar(300),
    estado_registro     varchar(20)  DEFAULT 'Activo',
    fecha_registro      timestamptz  DEFAULT now(),
    fecha_modificacion  timestamptz,
    version_registro    integer      DEFAULT 1,
    id_usuario_creador  bigint,
    id_usuario_modificacion bigint,
    CONSTRAINT ck_inscripcion_curso_estado
      CHECK (estado IN ('ACTIVA', 'RETIRADA', 'FINALIZADA')),
    -- Una baja sin fecha no se puede auditar ni revertir con criterio.
    CONSTRAINT ck_inscripcion_curso_baja
      CHECK (estado <> 'RETIRADA' OR fecha_baja IS NOT NULL)
);

COMMENT ON TABLE servicios_educativos.inscripcion_curso IS
  'Matrícula de un estudiante en una versión de curso. Es la fuente de la lista de asistencia: sin inscripción, un estudiante no aparece en la planilla de sus clases.';

-- ---------------------------------------------------------------------------
-- 2) Integridad
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inscripcion_curso_id_curso_version_fkey') THEN
    ALTER TABLE servicios_educativos.inscripcion_curso
      ADD CONSTRAINT inscripcion_curso_id_curso_version_fkey
      FOREIGN KEY (id_curso_version)
      REFERENCES servicios_educativos.curso_version(id_curso_version) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inscripcion_curso_id_estudiante_fkey') THEN
    -- RESTRICT igual que en asistencia: un estudiante con historial académico no
    -- se borra en cascada por accidente.
    ALTER TABLE servicios_educativos.inscripcion_curso
      ADD CONSTRAINT inscripcion_curso_id_estudiante_fkey
      FOREIGN KEY (id_estudiante)
      REFERENCES persona.persona_estudiante(id_persona) ON DELETE RESTRICT;
  END IF;
END $$;

-- Un estudiante se inscribe una vez por versión de curso. Si se retira y vuelve,
-- se reactiva la misma fila: así el historial no se parte en dos.
CREATE UNIQUE INDEX IF NOT EXISTS ux_inscripcion_curso_version_estudiante
  ON servicios_educativos.inscripcion_curso (id_curso_version, id_estudiante);

-- La planilla siempre consulta por versión de curso y estado.
CREATE INDEX IF NOT EXISTS ix_inscripcion_curso_version_estado
  ON servicios_educativos.inscripcion_curso (id_curso_version, estado);

-- ---------------------------------------------------------------------------
-- 3) Matrículas deducidas de lo ya vendido
-- ---------------------------------------------------------------------------

-- Las ventas de curso que ya existen son la mejor evidencia disponible de quién
-- está cursando. Se traen sólo cuando el cliente de la venta es efectivamente un
-- estudiante: si quien pagó fue el padre, no hay forma de saber por cuál de sus
-- hijos era, y adivinar sería peor que dejarlo para carga manual.
INSERT INTO servicios_educativos.inscripcion_curso
  (id_curso_version, id_estudiante, fecha_inscripcion, estado, observaciones)
SELECT DISTINCT ON (venta.id_curso_version, venta.id_cliente)
       venta.id_curso_version,
       venta.id_cliente,
       venta.fecha_venta,
       'ACTIVA',
       'Matrícula deducida de una venta previa al alta de inscripciones.'
FROM contabilidad.transaccion_venta venta
JOIN persona.persona_estudiante estudiante ON estudiante.id_persona = venta.id_cliente
WHERE venta.id_curso_version IS NOT NULL
  AND venta.id_cliente IS NOT NULL
  AND lower(COALESCE(venta.estado_registro, 'activo')) = 'activo'
ORDER BY venta.id_curso_version, venta.id_cliente, venta.fecha_venta
ON CONFLICT (id_curso_version, id_estudiante) DO NOTHING;

-- Quien ya tiene asistencia registrada en una clase, evidentemente cursa: sin
-- esto, una planilla existente perdería estudiantes al pasar a usar matrículas.
INSERT INTO servicios_educativos.inscripcion_curso
  (id_curso_version, id_estudiante, fecha_inscripcion, estado, observaciones)
SELECT DISTINCT ON (clase.id_curso_version, asistencia.id_estudiante)
       clase.id_curso_version,
       asistencia.id_estudiante,
       clase.fecha,
       'ACTIVA',
       'Matrícula deducida de una asistencia previa al alta de inscripciones.'
FROM servicios_educativos.asistencia_clase_curso asistencia
JOIN servicios_educativos.clase_curso clase ON clase.id_clase_curso = asistencia.id_clase_curso
WHERE COALESCE(asistencia.estado_registro, true) = true
ORDER BY clase.id_curso_version, asistencia.id_estudiante, clase.fecha
ON CONFLICT (id_curso_version, id_estudiante) DO NOTHING;

DO $$
DECLARE
  v_total integer;
BEGIN
  SELECT count(*) INTO v_total FROM servicios_educativos.inscripcion_curso;
  RAISE NOTICE 'inscripcion_curso lista con % matrícula(s).', v_total;
END $$;

-- ---------------------------------------------------------------------------
-- 4) Permisos del recurso
-- ---------------------------------------------------------------------------

INSERT INTO seguridad.permiso (codigo, descripcion, modulo, estado_registro)
VALUES
  ('SERVICIOS_EDUCATIVOS.INSCRIPCION_CURSO.CREATE', 'Permiso de API NestJS SERVICIOS_EDUCATIVOS.INSCRIPCION_CURSO.CREATE', 'SERVICIOS_EDUCATIVOS', 'Activo'),
  ('SERVICIOS_EDUCATIVOS.INSCRIPCION_CURSO.READ',   'Permiso de API NestJS SERVICIOS_EDUCATIVOS.INSCRIPCION_CURSO.READ',   'SERVICIOS_EDUCATIVOS', 'Activo'),
  ('SERVICIOS_EDUCATIVOS.INSCRIPCION_CURSO.UPDATE', 'Permiso de API NestJS SERVICIOS_EDUCATIVOS.INSCRIPCION_CURSO.UPDATE', 'SERVICIOS_EDUCATIVOS', 'Activo')
ON CONFLICT (codigo) DO UPDATE SET estado_registro = 'Activo';

-- Se concede a los mismos roles que ya administran las clases del curso: quien
-- puede crear una clase es quien matricula. Así no hace falta mantener una
-- segunda lista de roles que se desincronice de la primera.
INSERT INTO seguridad.rol_permiso (id_rol, id_permiso)
SELECT DISTINCT rol_clase.id_rol, nuevo.id_permiso
FROM seguridad.rol_permiso rol_clase
JOIN seguridad.permiso permiso_clase
  ON permiso_clase.id_permiso = rol_clase.id_permiso
 AND permiso_clase.codigo LIKE 'SERVICIOS_EDUCATIVOS.CLASE_CURSO.%'
JOIN seguridad.permiso nuevo
  ON nuevo.codigo = replace(permiso_clase.codigo, 'CLASE_CURSO', 'INSCRIPCION_CURSO')
ON CONFLICT DO NOTHING;
